name: ARM64 BusyBox RootFS (FINAL STABLE)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install toolchain
      run: |
        sudo apt update
        sudo apt install -y gcc-aarch64-linux-gnu wget

    - name: Download BusyBox
      run: |
        wget https://busybox.net/downloads/busybox-1.36.1.tar.bz2
        tar -xf busybox-1.36.1.tar.bz2

    - name: Configure BusyBox (Static)
      run: |
        cd busybox-1.36.1
        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- defconfig
        
        # 强制静态
        sed -i 's/# CONFIG_STATIC is not set/CONFIG_STATIC=y/' .config

    - name: Build BusyBox
      run: |
        cd busybox-1.36.1
        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j2

    - name: Install to rootfs
      run: |
        mkdir rootfs
        cd busybox-1.36.1
        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CONFIG_PREFIX=../rootfs install

    - name: Add basic files
      run: |
        mkdir -p rootfs/{proc,sys,dev,tmp,root}
        echo "root:x:0:0:root:/root:/bin/sh" > rootfs/etc/passwd
        echo "root:x:0:" > rootfs/etc/group

    - name: Package
      run: |
        tar -czf busybox-rootfs-arm64.tar.gz rootfs
        file rootfs/bin/busybox

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: busybox-rootfs-arm64
        path: busybox-rootfs-arm64.tar.gz
